### ISSUE TITLE
Number of locked LSK is incorrect

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-mobile#1178] opened 2021-12-16 19:27 UTC
### Expected behavior
The locked number should show all the locked tokens
### Actual behavior
It shows only unlockable tokens
### Steps to reproduce
![image](https://user-images.githubusercontent.com/25085095/146435579-23c27ce8-ba9f-4fe7-a4f4-a694f5514cba.png)
 This account has 50LSK ready to unlock and 1130LSK locked by voting 
 https://testnet.liskscan.com/account/lskhf3gtj3wecxaxy7csqb5k8kszugghpscvat5b4

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15, lisk mobile 2.0.0

**Comment by ManuGowda** [comment] 2021-12-16 19:33
@Balanced02 here is the account summary for `lskhf3gtj3wecxaxy7csqb5k8kszugghpscvat5b4`

```
Total Balance
213,115.5225LSK

Total Available
211,985.5225LSK
99.46%

Total Unlocking
50LSK
0.02%

Total Locked
1,080LSK
0.5%
```

**Comment by Balanced02** [comment] 2021-12-28 10:40
@przemerr

Can you please cross-check, I tested this and the details here are correct.

Please see screenshots below.
![Simulator Screen Shot - iPhone 12 - 2021-12-28 at 11 38 11](https://user-images.githubusercontent.com/28750984/147557934-b807072f-2d88-425c-ad97-4f8ade5a97a7.png)
![Simulator Screen Shot - iPhone 12 - 2021-12-28 at 11 38 15](https://user-images.githubusercontent.com/28750984/147557937-a89b81cc-f5e3-4075-a463-24fe678377d2.png)

cc: @ManuGowda

**Comment by przemerr** [comment] 2021-12-28 10:44
Yes, the reported numbers are correct now, there was a recent testflight update which fixed the issue.👍

**Comment by ManuGowda** [comment] 2021-12-28 11:13
Since the issues doesn't exits/not reproducible, closing it for now.

**Closed by ManuGowda** 2021-12-28 11:13 UTC
Labels: type: bug, unplanned
