### ISSUE TITLE
Reveal QR code doesn't work as indented

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-mobile#1185] opened 2021-12-17 09:51 UTC
### Expected behavior
User should be able to see the generated QR code
### Actual behavior
The QR code is generated but it's very hard to scroll down to see it
### Steps to reproduce
Go to backup you passphrase section in the settings, click `Reveal QR code`
![0](https://user-images.githubusercontent.com/25085095/146525120-3a956378-fd2c-41af-a7ee-aa05ad53d212.jpg)
![0](https://user-images.githubusercontent.com/25085095/146525170-8e5c190b-712b-488c-a515-74c6cd69ad02.jpg)

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15, mobile 2.0.0

**Comment by ManuGowda** [comment] 2021-12-17 14:11
This issue is duplicate of #1180 , this can be closed one #1180 is resolved and tested

**Closed** 2021-12-29 10:26 UTC
Labels: type: bug
