### ISSUE TITLE
The back button in the register page doen't work

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#1099] opened 2021-09-30 14:34 UTC
### Expected behavior
I should be able to go from the register page to the login page.

### Actual behavior
I can navigate back and forth through different steps of the register screen. But I can't go from the register screen to the login.

### Steps to reproduce
- Go to the register screen.
- Navigate to the next step.
- Get back to the first step and the to the login page.
- The back button doesn't work.

### Which version(s) does this affect? (Environment, OS, etc...)
Latest development.

**Comment by ManuGowda** [comment] 2021-11-28 16:13
This issues seems to be duplicate of https://github.com/LiskHQ/lisk-mobile/issues/1152.
@Balanced02 once you confirm both issues are same, please close https://github.com/LiskHQ/lisk-mobile/issues/1152

**Comment by Balanced02** [comment] 2021-12-02 22:37
@ManuGowda 

This is a duplicate of #1152 , closing this issue.

**Closed** 2021-12-02 22:37 UTC
