### ISSUE TITLE
Review and update repository badges 

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-mobile#1320] opened 2022-03-29 13:06 UTC
### Description
Some of the badge seem out of date. We should make sure they're all up to date.

### Motivation
Keep project general information up to date and valid.

**Comment by ManuGowda** [comment] 2022-12-19 13:23
@reyraa the badges seems ok https://github.com/LiskHQ/lisk-mobile#lisk-mobile

could you please share more info on what needs to be addressed?

**Comment by ManuGowda** [comment] 2023-04-26 08:04
Duplicate of https://github.com/LiskHQ/lisk-mobile/issues/1723
badges should be updated with this PR

**Closed by ManuGowda** 2023-04-26 08:04 UTC
Labels: type: duplicate
