### ISSUE TITLE
Fix `iMessage` extension

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1463] opened 2022-08-29 12:10 UTC
### Expected behavior
A user should be able to show a specific transaction detail based on a link sent via iMessage on iOS.

### Actual behavior
The feature is broken and not being supported for a while.

We need to re-evaluate and investigate the way we will be handling the functionality, since the current implementation is broken and seems not to be more industry-suported.

### Which version(s) does this affect? (Environment, OS, etc...)
All versions.

**Comment by ManuGowda** [comment] 2023-02-21 09:50
This is a duplicate of https://github.com/LiskHQ/lisk-mobile/issues/552

**Closed by ManuGowda** 2023-02-21 09:50 UTC
Labels: type: duplicate
