### ISSUE TITLE
Migrate home connection error  to the new design

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-mobile#754] opened 2019-04-17 14:31 UTC
This is a subtask of #746
The goal is to migrate home connection error to the new design according to the designs here:
https://projects.invisionapp.com/d/main#/console/17093670/354341348/preview

**Comment by reyraa** [comment] 2019-06-18 08:13
Duplicate of #749

**Closed by reyraa** 2019-06-18 08:13 UTC
Labels: duplicate
