### ISSUE TITLE
Token transfer message change don't update transaction fees

### ISSUE THREAD

**Issue by ClementeSerrano** [LiskHQ/lisk-mobile#1958] opened 2023-07-31 10:15 UTC
### Expected behavior
When changing the "Message" field on the token transfer form, the fees estimations should be recalculated (refetched from service) so the app shows updated values to the user.

### Actual behavior
Message field change don't trigger an estimate-fees API refetch.

E2E tests are also not verified to pass. We need to adapt them.

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by sridharmeganathan** [comment] 2023-08-28 09:53
Duplicate of #2010

**Closed by sridharmeganathan** 2023-08-28 09:53 UTC
Labels: type: bug, type: duplicate
